- name: Create a VIP, pool, pool members and nodes
  hosts: 192.168.0.2
  connection: local
  
  - tasks:
   - name: Create a pool
     bigip_pool:
         lb_method: "ratio_member"
         name: "web"
         password: "default"
         server: "192.168.0.2"
         slow_ramp_time: "120"
         user: "admin"
         validate_certs: "no"
         
         
